name: BUG 反馈
description: 使用此模板反馈 BUG，若未使用将会直接关闭 issues
labels: [ "bug" ]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
          required: true
        - label: |
            我已使用最新测试版（[下载链接](https://dl.schale.top/baad/develop)），并且使用最新测试版时该 bug 仍然未被修复
          required: true
  - type: textarea
    id: describe
    attributes:
      label: 问题描述
      description: 尽可能详细描述你的问题
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: 系统信息
      description: 请说明你所使用的安卓系统信息
      value: |
        - 安卓版本：
        - 系统版本：
        - 手机型号：
        - 屏幕分辨率：
    validations:
      required: true
  - type: textarea
    id: repeat
    attributes:
      label: 复现步骤
      description: |
        请输入该问题是如何被引发的
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志文件
      description: |
        请提供 [bugreport](https://developer.android.google.cn/studio/debug/bug-report?hl=zh-cn) 日志，
        或下载 adb 并使用 `adb.exe logcat -b crash`（针对于应用崩溃问题）`adb.exe logcat *:W`（针对于一般问题）
        **请直接将完整的文件拖拽进来，而非自己裁切或复制的片段；若文件体积过大可压缩后再上传**
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 截图
      description: |
        如果有，添加屏幕截图以帮助解释你的问题
    validations:
      required: false
